### ISSUE TITLE
Run Extension Type needs inputAnalyses implemented

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/song-search#13]
`inputAnalyses` is currently set to a string type with a hard-coded "not implemented" return string. This field should be a list of Analyses that were used as input to this workflow. Every run has workflow params which container fields such as `analysisId` or `normal_aln_analysis_id` and `tumour_aln_analysis_id`, potentially more in the future. When Apollo federation use an extension object you have access to all the fields you are extending inside your service, meaning that it is possible to extend the Run type like this:

```
type Run @key(fields: "runId") @extends {
    runId: ID! @external
    parameters: JSON @external
    producedAnalyses: [Analysis]
    inputAnalyses: [Analysis]
}
```

This would mean that you would add to the entity resolver for the Run type to populate the inputAnalyses by looking for keys that match the above noted inputs and using their values to compile a list of analyses to return back from this service.

It is possible that the keys you are looking for will not be there in the parameters JSON so it is important to handle that scenario, essentially you are looking to:

* compile a list of key/vals present in the `parameters` JSON (Map<String, Object>) if the key is one of the list of searchable analysis input fields(`analysis_id`, `normal_aln_analysis_id`, `tumour_aln_analysis_id`)
* fetching each matching analysis (vals from list of keys/vals) and returning as List<Analysis>

**Comment by jaserud** [comment]
To test, use the updated `inputAnalyses` field (see e.g. below) and see that it actually returns the inputAnalyses and not just a string

```
query{
  analyses(filter:{analysisId:"fb4c8462-ebe7-471c-8c84-62ebe7671c91"}) {
    analysisId
    inputForRuns {
      runId
      inputAnalyses {
        analysisId
      }
    }
  }
}
```

**Comment by jaserud** [comment]
closed because this is already deployed to prod
