### ISSUE TITLE
Add git tagging from Jenkins pipeline for song-search and rdpc-gateway

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/song-search#27]
really at 2.1.0, github says 2.0,0

![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/e3c63a9a-756f-40e5-ab01-d45295bd6de5)

**Comment by akachru-github** [comment]
The pipelines for tag and publishing docker images are not failing, might be some issue with the logic of the pipeline. Adding to ready for implementation, at a lower priority than the molecular data release backup tasks. .

**Comment by yalturmes** [comment]
I only understand new version release process on a high level but I can tell that a new **git** version tag should have been introduced (incremented) as part of the release process. Based on pom.xml in song-search repo and dockerhub repo there have been a few releases since 2.0.0 so it looks like the git version tagging have been overlooked or omitted during last couple of releases for song-search.
@rosibaj , this looks like a problem that will need to be addressed by the development team working on song-search. Let me know if I can help on my end though. Re-assigning the ticket back to you.

**Comment by rosibaj** [comment]
@yalturmes discussed with dusan - there is an issue and the jenkins file needs to be updated.  this is in some other repositories as well, so @andricDu will reach out and show you exactly what needs to be updated.

**Comment by yalturmes** [comment]
After a brief conversation with @andricDu , It was clarified that the additional Jenkins step is required to enable git tagging functionality for song-search pipeline. This has already been configured for most pipelines and at this stage so we are looking to add this step in pipelines/repos where missing. This is an example of how this is configured for ego pipeline:
https://github.com/icgc-argo/workflow-management/blob/develop/Jenkinsfile#L108-L111

The ticket scope has changed to following:
* Audit and identify pipelines and corresponding git repos that are missing `git tag` step
* Apply necessary changes in Jenkinsfile to enable git tagging

After auditing all pipelines configuration in RDPC DEV/QA, following has been identified:
RDPC pipelines that already do `git tag` step:
* https://github.com/icgc-argo/rdpc-status
* https://github.com/icgc-argo/workflow-docs
* https://github.com/icgc-argo/workflow-gateway
* https://github.com/icgc-argo/workflow-management
* https://github.com/icgc-argo/workflow-relay
* https://github.com/icgc-argo/workflow-search
* https://github.com/icgc-argo/workflow-ui

RDPC pipelines that don't do `git tag` step:
* https://github.com/icgc-argo/rdpc-gateway
* https://github.com/icgc-argo/song-search

So beside the initially reported song-search repo missing `git tag` step, the ticket scope now extends to rdpc-gateway too.

Additionally it is necessary to clarify if the following pipelines/repos require git tagging:
* https://github.com/icgc-argo/workflow-graph-parent-pom.git
* https://github.com/icgc-argo/workflow-graph-lib.git

@andricDu - would you be able to provide input on this?

**Comment by akachru-github** [comment]
@andricDu , have you had a chance to review @yalturmes 's PR's?

**Comment by yalturmes** [comment]
All PRs have been merged. Ticked closed.
