### ISSUE TITLE
🐛 Should Suppressed (and eventually Deleted) Analyses be indexed in RDPC?

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/song-search#35]
## Describe the bug
When an analysis is SUPPRESSED, it is not indexed by the RDPC API.

This causes some issues when reporting with the rdpc-api that could affect how decisions are made in automation activation/filter/decider logic or for administrative auditing processes {see example below to see how it looks confusing. 

I think in the long-run, it will also be imported to incorporate the deleted state as well. 

## Steps To Reproduce
Query Prod API: 
```
query{
  analyses(filter: {analysisId:"47b6ad0f-0322-4ea4-b6ad-0f03220ea4a7"}){
    analysisId
    studyId
    analysisType
  }
  runs(filter:{runId:"wes-b8ab3acc49f74acab0e417590fc82768"}){
    runId
    state
    startTime
    completeTime
    inputAnalyses{
      analysisId
      analysisType
    }
    producedAnalyses{
      analysisId
      analysisType
    }
  }
}
```

See Results: 
![image](https://user-images.githubusercontent.com/15824252/96606705-9144e200-12c5-11eb-86e0-b8a33949d4d5.png)

## Expected behavior
NEEDS DISCUSSION

**Comment by andricDu** [comment]
My opinion is that the RDPC API should be able to present the whole truth. Analysis regardless of their state should be viewable and searchable. On top of that, deleting analyses through the deletion of the underlying persisted data is misguided as it orphans runs as runs do not get deleted.

**Comment by andricDu** [comment]
If there is a need to "archive" runs as a super duper suppressed terminal state where by default they do not show up in results unless some kind of `showArchived: true` query param is passed then we can definitely solve that, as this "deleting" feature is a presentation layer problem.

**Comment by rosibaj** [comment]
@andricDu the DELETED state was specifically discussed bc in the case of some REDACTIONS we will be required to remove even metadata about produced files - lets discuss with Christina what the legal obligation is here so we can get it correctly clarified.

**Comment by andricDu** [comment]
https://github.com/icgc-argo/rdpc-infra/commit/36929bef115d9522543873bac87d4a50c55c0050

**Comment by andricDu** [comment]
![image.png](https://images.zenhubusercontent.com/59ccfffeb0222d5de4797e77/b84e49d9-8cc5-466a-858c-6166462ee18c)
