### ISSUE TITLE
🐛 Query info.totalHits caps at 10000 if index has more than 10000 documents

### ISSUE THREAD

**Issue by jaserud** [icgc-argo/song-search#51]
## Describe the bug
If index has more then 10000 documents, the `info.totalHits` only returns 10000 as value even if there are actaully more than that.

Example using it on an index where files_centric index has more than 10000 documents:
![image](https://user-images.githubusercontent.com/34698315/123691530-b8c05700-d823-11eb-973d-ef3911d75f4d.png)

This is only an issue if file_centric (or analysis_centric) has more than 10000 documents.

## Steps To Reproduce

Steps to reproduce the behaviour:
1. connect song-search to es with file and analysis indices  each one with more than 10000 documents
2. run query like in example above. So, query with page `from` > 10000 and query for info.totalHits
3. See the incorrect response

## Expected behaviour
Should return correct number of total hits. The bug is most likely due to elastic search and its 10000 query limit so the fix might be their.

Note: this could be an issue in workflow-search too, but need to check.

**Comment by rosibaj** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/7.5/search-request-body.html#request-body-search-track-total-hits

**Comment by jaserud** [comment]
For aggregations, `track_total_hits` is need if we want `totalHits` to be correct from search:
![image](https://user-images.githubusercontent.com/34698315/126543166-aca37bc1-9f9b-4d00-a2d6-2be6060759ad.png)

However, we will still get an error if aggregation returns more buckets than `max_buckets`
![image](https://user-images.githubusercontent.com/34698315/126543297-4841de34-9252-4a04-b693-e1d5b63d5576.png)

**Comment by rosibaj** [comment]
@jaserud thanks  - i guess song-search is not using any buckets explicitly, but should we set this to be the same as `totalhits` anyways?

**Comment by jaserud** [comment]
@rosibaj The `search.max_bucket` is actually a cluster wide config, and I'm not sure how it affects the cluster so I think it might need a bit more thinking before setting it to a default for song-search. The default for this value is supposed to be [65,536](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/search-settings.html#search-settings-max-buckets) actually. 

Currently song-search has no bucket aggs. Workflow search has one on the run.states (bucket runs by states) and there are only a dozen or so [states](https://github.com/ga4gh/workflow-execution-service-schemas/blob/c3b19854240c4fcbaf3483e22b19db0a918a7ee5/openapi/workflow_execution_service.swagger.yaml#L485). 

So my two cents, I think the current rdpc-gateway shouldn't have any issues with the default max_buckets so I think we can leave it their :thinking:.

**Comment by jaserud** [comment]
This fix was released in 2.6.0 which has already been released to prod
