### ISSUE TITLE
Get Matched Tumour/Normal Pairs by Donor ID

### ISSUE THREAD

**Issue by joneubank** [icgc-argo/song-search#67]
Add a query that takes donorId as input and returns an array of matched tumour/normal pairs for that Donor.

**Comment by jaserud** [comment]
Unexpected behavior observed with this query:
```
query { sampleMatchedAnalysesForDonor(
  req: {
    donorId: "DO262418",
    analysisType: "sequencing_experiment"
  }
) {
    normalSampleAnalysis{
      analysisId
      studyId
      analysisType
      analysisState
      donors {
        donorId
        submitterDonorId
      }
    }
    tumourSampleAnalysis{
      studyId
      analysisId
      analysisType
      analysisState
      donors {
        donorId
        submitterDonorId
      }
    }
  }
}
```
Query matched samples across studies and with different donorIds:
![image](https://user-images.githubusercontent.com/34698315/162470525-29de1a6d-d41b-4ed0-b6d2-21ad6d9abb20.png)

There is bad data here, but the query should filter the pairs to match the sampleId and donorIds. 
Also add optional studyId to filter pairs matched across studies.

**Comment by jaserud** [comment]
Add sampleType to request and add constraint to check sampleTypes are equal for matching samples.
https://github.com/icgc-argo/song-search/pull/75

**Comment by b-f-chan** [comment]
Released to prod, closing
